import { ed25519 } from "@noble/curves/ed25519";
import { sha256 } from "@noble/hashes/sha256";
import { bytesToHex, hexToBytes } from "@noble/hashes/utils";
import type {
  AuditEventRepository,
  AuditEvent,
  SigningKeyRepository,
} from "@renatus/db";
import { canonicalJson } from "@renatus/shared";
import {
  AuditorError,
  AuditorEventRetrievalError,
  AuditorReportGenerationError,
} from "./errors.js";
import { getOrCreateJobKeypair, signCanonicalText } from "./sign.js";
import {
  type AuditEventRecord,
  type AuditorInput,
  type AuditorOutput,
  type AuditReport,
  type AuditReportSummary,
  type Signature,
} from "./types.js";

/**
 * Auditor agent — produces cryptographically signed audit reports
 * over the per-job append-only event log.
 *
 * Responsibilities:
 *   1. Load the audit_events rows for a job (empty is valid — empty
 *      audits are still signed and verifiable).
 *   2. Get-or-create the job's ed25519 keypair via `SigningKeyRepository`.
 *      When `RENATUS_KEK` is set, the private key is encrypted at rest;
 *      otherwise it's plaintext + a loud warning.
 *   3. Compute summary statistics grouped by agent and event type.
 *   4. Build the `AuditReport`, canonicalize it via `canonicalJson()`,
 *      hash with SHA-256, and sign with ed25519.
 *   5. Best-effort emit an `audit_signed` event back into audit_events.
 *
 * The signature proves:
 *   - The audit report was generated by a Renatus runtime holding the
 *     job's private key.
 *   - The report has not been tampered with.
 *   - The report is tied to a specific job and timestamp.
 *
 * Sandbox execution against the migrated repo (re-running tests inside
 * a hermetic Vercel Sandbox / WebContainer) is a Wave 4 deliverable
 * and is intentionally out of scope here.
 *
 * Verification:
 *   Anyone with the public key can verify the signature via
 *   `AuditorService.verifySignature(report, signature)`.
 */
export class AuditorService {
  constructor(
    private readonly auditEventRepo: AuditEventRepository,
    private readonly signingKeyRepo: SigningKeyRepository,
  ) {}

  async audit(input: AuditorInput): Promise<AuditorOutput> {
    try {
      const events = await this.retrieveAuditEvents(input.jobId);

      const { privateKey, publicKey } = await this.getOrCreateKeypair(
        input.jobId,
      );

      const auditReport = this.generateAuditReport(
        input.jobId,
        input.snapshotId,
        events,
      );

      const { signature, canonicalReportBytes } = this.signAuditReport(
        auditReport,
        privateKey,
        publicKey,
      );

      await this.recordSignatureEvent(
        input.jobId,
        signature,
        canonicalReportBytes,
        auditReport.timestamp,
      );

      return {
        jobId: input.jobId,
        auditReport,
        signature,
        // Web app builds shareable URLs (Wave 4); the agent returns null.
        auditUrl: null,
      };
    } catch (error) {
      if (error instanceof AuditorError) {
        throw error;
      }
      throw new AuditorError("Audit failed", error);
    }
  }

  /**
   * Load the event log for a job. An empty log is a valid audit (the
   * Auditor will sign an empty report); only true DB failures throw.
   */
  private async retrieveAuditEvents(jobId: string): Promise<AuditEvent[]> {
    try {
      return await this.auditEventRepo.findByJobId(jobId);
    } catch (error) {
      throw new AuditorEventRetrievalError(jobId, error);
    }
  }

  /**
   * Get the existing ed25519 keypair for a job, or generate + persist
   * a fresh one. Delegates to the shared `getOrCreateJobKeypair` helper so
   * the Auditor and Q&A agents share one signing-key lifecycle. KEK +
   * plaintext-warning behaviour is identical to the pre-extraction code.
   */
  private async getOrCreateKeypair(jobId: string): Promise<{
    privateKey: Uint8Array;
    publicKey: Uint8Array;
  }> {
    return getOrCreateJobKeypair(this.signingKeyRepo, jobId, "Auditor");
  }

  /**
   * Group counts by agentKind and eventType and produce a stable
   * `AuditReportSummary`. The high-value rollups (patches, tests,
   * failures) are computed from the event-type tallies — no hardcoded
   * per-agent shortcuts.
   */
  private generateAuditReport(
    jobId: string,
    snapshotId: string,
    events: AuditEvent[],
  ): AuditReport {
    try {
      const byAgent: Record<string, number> = {};
      const byEventType: Record<string, number> = {};

      for (const event of events) {
        byAgent[event.agentKind] = (byAgent[event.agentKind] ?? 0) + 1;
        byEventType[event.eventType] = (byEventType[event.eventType] ?? 0) + 1;
      }

      const summary: AuditReportSummary = {
        totalEvents: events.length,
        byAgent,
        byEventType,
        patchesProposed: byEventType["patch_proposed"] ?? 0,
        patchesApplied: byEventType["patch_applied"] ?? 0,
        patchesUnresolved: byEventType["patch_unresolved"] ?? 0,
        testsGenerated: byEventType["test_generated"] ?? 0,
        testsPassed: byEventType["test_passed"] ?? 0,
        testsFailed: byEventType["test_failed"] ?? 0,
        failures: Object.entries(byEventType)
          .filter(([type]) => type.endsWith("_failed"))
          .reduce((sum, [, count]) => sum + count, 0),
      };

      // Re-shape DB rows into the Zod-typed event-record shape (no `any`).
      const eventRecords: AuditEventRecord[] = events.map((e) => ({
        id: e.id,
        jobId: e.jobId,
        agentKind: e.agentKind,
        eventType: e.eventType,
        // rationale: jsonb columns come back typed as `unknown` from drizzle; we narrow to Record at the seam.
        payload: e.payload as Record<string, unknown>,
        timestamp: e.timestamp,
        entityId: e.entityId,
        entityType: e.entityType,
      }));

      return {
        jobId,
        snapshotId,
        timestamp: new Date().toISOString(),
        summary,
        events: eventRecords,
      };
    } catch (error) {
      throw new AuditorReportGenerationError(
        error instanceof Error ? error.message : "Unknown error",
        error,
      );
    }
  }

  /**
   * Canonicalize the report, hash with SHA-256, and sign with ed25519.
   * Delegates the hash+sign step to the shared `signCanonicalText` helper;
   * canonicalization stays here so the report's exact byte sequence is the
   * domain decision of the Auditor (the same bytes get re-hashed inside
   * `verifySignature`). Behaviour is byte-for-byte identical to the
   * pre-extraction code; only `signedAt` (a fresh ISO timestamp) differs
   * between runs.
   *
   * Also returns the canonical-JSON byte sequence so the caller can persist
   * it on the `audit_signed` event payload. Verifiers MUST re-canonicalize
   * from that exact byte sequence — the rebuild-from-events path is lossy on
   * `report.timestamp` (DB clock != in-process clock) and would otherwise
   * mis-match the signature's `messageHash`.
   */
  private signAuditReport(
    auditReport: AuditReport,
    privateKey: Uint8Array,
    publicKey: Uint8Array,
  ): { signature: Signature; canonicalReportBytes: string } {
    const canonicalReportBytes = canonicalJson(auditReport);
    const baseSignature = signCanonicalText(
      canonicalReportBytes,
      privateKey,
      publicKey,
    );
    return {
      signature: { ...baseSignature, canonicalReportBytes },
      canonicalReportBytes,
    };
  }

  /**
   * Best-effort emit an `audit_signed` event. The signature itself is
   * the source of truth — if recording the event fails (e.g. DB blip),
   * we log and continue rather than fail the whole audit.
   *
   * The payload includes the exact canonical-JSON bytes that were signed
   * (`canonicalReportBytes`) plus the original `report.timestamp` so the
   * `/api/jobs/[jobId]/audit-report` route can return a byte-for-byte
   * faithful representation of what was signed — without it, verifiers
   * canonicalizing the rebuilt report would hit `report.timestamp` drift
   * (DB clock != in-process clock) and the messageHash would mis-match.
   */
  private async recordSignatureEvent(
    jobId: string,
    signature: Signature,
    canonicalReportBytes: string,
    reportTimestamp: string,
  ): Promise<void> {
    try {
      await this.auditEventRepo.create({
        jobId,
        agentKind: "auditor",
        eventType: "audit_signed",
        payload: {
          algorithm: signature.algorithm,
          value: signature.value,
          publicKey: signature.publicKey,
          messageHash: signature.messageHash,
          signedAt: signature.signedAt,
          // NEW — the canonical bytes that were hashed + signed. Lets
          // verifiers reproduce verification byte-for-byte.
          canonicalReportBytes,
          // NEW — redundant with the canonical bytes (they encode the
          // timestamp) but cheap and self-documenting at query time.
          reportTimestamp,
          // Legacy keys retained for one release so any consumer still
          // reading the old shape (e.g. the audit-report API route before
          // the matching W5 update) keeps working. Safe to drop after one
          // deploy cycle.
          signatureHex: signature.value,
          publicKeyHex: signature.publicKey,
          messageHashHex: signature.messageHash,
        },
        entityId: null,
        entityType: null,
      });
    } catch (error) {
      console.warn(
        `[Auditor] Failed to record audit_signed event for jobId=${jobId}: ${
          error instanceof Error ? error.message : String(error)
        }`,
      );
    }
  }

  /**
   * Verify a signature over an `AuditReport`.
   *
   * Preferred path: `signature.canonicalReportBytes` is present (the
   * persisted path — see `recordSignatureEvent`). We hash THOSE exact bytes
   * and ignore the rebuilt-from-events `auditReport`. This sidesteps the
   * `report.timestamp` drift bug — the rebuild path uses the
   * `audit_signed` row's DB-clock timestamp, which is microseconds away
   * from the in-process `new Date()` that was originally signed.
   *
   * Fallback path: no `canonicalReportBytes` (in-memory verifier
   * roundtrips, or legacy signed events written before the field
   * existed). We re-canonicalize the supplied report — which is correct
   * iff the caller hasn't lost timestamp fidelity.
   *
   * Either path re-checks the SHA-256 hash so verifiers don't need to
   * trust the declared `messageHash`.
   */
  static verifySignature(
    auditReport: AuditReport,
    signature: Signature,
  ): boolean {
    try {
      const canonical =
        typeof signature.canonicalReportBytes === "string"
          ? signature.canonicalReportBytes
          : canonicalJson(auditReport);
      const messageHash = sha256(canonical);
      const expectedHashHex = bytesToHex(messageHash);

      if (expectedHashHex !== signature.messageHash.toLowerCase()) {
        return false;
      }

      const signatureBytes = hexToBytes(signature.value);
      const publicKeyBytes = hexToBytes(signature.publicKey);

      return ed25519.verify(signatureBytes, messageHash, publicKeyBytes);
    } catch {
      return false;
    }
  }
}
