import { drizzle } from "drizzle-orm/neon-http";
import { neon } from "@neondatabase/serverless";
import { eq } from "drizzle-orm";
import { migrationPlans, type MigrationPlanRow, type NewMigrationPlan } from "../schema/migration-plans.js";

/**
 * Repository for migration plans
 *
 * Handles persistence and retrieval of migration plans generated by the Cartographer.
 */
export class MigrationPlanRepository {
  private db;

  constructor(databaseUrl: string) {
    const sql = neon(databaseUrl);
    this.db = drizzle(sql);
  }

  /**
   * Save a migration plan to the database
   *
   * @param plan - The migration plan to save (from @renatus/shared MigrationPlan type)
   * @returns The saved plan row
   */
  async save(plan: {
    id: string;
    jobId: string;
    ecosystem: string;
    fromVersion: string;
    toVersion: string;
    rules: any[];
    createdAt: Date;
  }): Promise<MigrationPlanRow> {
    const newPlan: NewMigrationPlan = {
      id: plan.id,
      jobId: plan.jobId,
      ecosystem: plan.ecosystem,
      fromVersion: plan.fromVersion,
      toVersion: plan.toVersion,
      rules: plan.rules as any, // rationale: JSONB type compatibility
      createdAt: plan.createdAt,
    };

    const [inserted] = await this.db
      .insert(migrationPlans)
      .values(newPlan)
      .returning();

    if (!inserted) {
      throw new Error("Failed to insert migration plan");
    }

    return inserted;
  }

  /**
   * Get a migration plan by job ID
   * 
   * @param jobId - The job ID to search for
   * @returns The migration plan if found, null otherwise
   */
  async getByJobId(jobId: string): Promise<MigrationPlanRow | null> {
    const [plan] = await this.db
      .select()
      .from(migrationPlans)
      .where(eq(migrationPlans.jobId, jobId))
      .limit(1);

    return plan ?? null;
  }

  /**
   * Get a migration plan by its ID
   * 
   * @param id - The plan ID to search for
   * @returns The migration plan if found, null otherwise
   */
  async getById(id: string): Promise<MigrationPlanRow | null> {
    const [plan] = await this.db
      .select()
      .from(migrationPlans)
      .where(eq(migrationPlans.id, id))
      .limit(1);

    return plan ?? null;
  }
}

// Made with Bob
